steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/5tran:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/5tran:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '5tran'
      - '--image'
      - 'gcr.io/$PROJECT_ID/5tran:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ACCESS_PASSWORD=$$ACCESS_PASSWORD,FIVETRAN_API_SECRET_BASE64=$$FIVETRAN_API_SECRET_BASE64,FIRECRAWL_API_KEY=$$FIRECRAWL_API_KEY,GEMINI_API_KEY=$$GEMINI_API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/5tran:$COMMIT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'

