openapi: 3.0.0
info:
  title: SaaS Metrics API
  version: 1.0.0
  description: SaaS application API for users, subscriptions, and usage tracking

servers:
  - url: https://api.saas-example.com/v1

security:
  - apiKey: []

paths:
  /users:
    get:
      summary: List users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /subscriptions:
    get:
      summary: List subscriptions
      responses:
        '200':
          description: List of subscriptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'

  /usage:
    get:
      summary: List usage events
      responses:
        '200':
          description: List of usage events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsageEvent'

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        company:
          type: string
        created_at:
          type: string
          format: date-time
        status:
          type: string
          enum: [active, inactive, trial]

    Subscription:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        plan:
          type: string
          enum: [starter, professional, enterprise]
        mrr:
          type: number
          description: Monthly recurring revenue
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        status:
          type: string
          enum: [active, cancelled, expired]

    UsageEvent:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        event_type:
          type: string
        timestamp:
          type: string
          format: date-time
        properties:
          type: object
          additionalProperties: true

